"""D1 probe: generate the post-edit Outlook reply-draft AppleScript and execute it.

Runs the production ``OutlookCompositionScripts.reply_to_email_script``
against a real Outlook inbox message id and executes the resulting
AppleScript via ``osascript``. The point is to (a) prove the rewritten
script doesn't hang the AppleEvent layer the way the readback+open+
activate version did and (b) leave a real draft in the user's Drafts
folder for visual confirmation.

Safety: the script writes a draft only -- it never calls ``send``.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC = REPO_ROOT / "src"
sys.path.insert(0, str(SRC))

# Import after sys.path setup so the package resolves the same way the
# running API resolves it.
from api.services.agent_processing.tools.direct_application_interactions.email_integration.outlook.script_generation.composition_scripts import (  # noqa: E402
    OutlookCompositionScripts,
)


def _applescript_escape(value: str) -> str:
    """Mirror the escaping the production OutlookScriptGenerator uses."""
    return (value or "").replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--email-id",
        required=True,
        help="Outlook inbox message id to reply to (from the listing probe).",
    )
    parser.add_argument(
        "--reply-all",
        action="store_true",
        help="Use 'reply all' instead of 'reply'.",
    )
    parser.add_argument(
        "--body",
        default=(
            "[D1 probe] This is a test reply draft generated by the "
            "post-edit Outlook reply script to validate that draft "
            "creation no longer hangs the AppleEvent layer. Safe to "
            "discard."
        ),
        help="Reply body content to write into the draft.",
    )
    parser.add_argument(
        "--timeout-seconds",
        type=int,
        default=45,
        help="Hard wall-clock timeout for the osascript invocation.",
    )
    args = parser.parse_args()

    generator = OutlookCompositionScripts(_applescript_escape)
    applescript = generator.reply_to_email_script(
        email_id=args.email_id,
        reply_body=args.body,
        reply_all=args.reply_all,
        draft_only=True,
    )

    print("=== Generated AppleScript ===")
    print(applescript)
    print("=== Executing via osascript ===")

    try:
        result = subprocess.run(
            ["osascript", "-e", applescript],
            capture_output=True,
            text=True,
            timeout=args.timeout_seconds,
        )
    except subprocess.TimeoutExpired:
        print(
            "TIMEOUT: osascript did not return within "
            f"{args.timeout_seconds}s -- this is the hang we are testing for."
        )
        return 2

    print(f"exit_code={result.returncode}")
    print(f"stdout={result.stdout!r}")
    print(f"stderr={result.stderr!r}")
    if "SUCCESS" in result.stdout:
        print(
            "RESULT: SUCCESS -- script returned. Visually verify in "
            "Outlook's Drafts folder."
        )
        return 0
    print("RESULT: NOT SUCCESS -- inspect stdout/stderr above.")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
