export { default as DrawingWindow } from './DrawingWindow';
export { default as DrawingPanel } from './DrawingPanel';
export { default as BasilWireframeWrapper } from './BasilWireframeWrapper';
export { default as StepCounter } from './StepCounter';
export { default as AnimatedStepLabel } from './AnimatedStepLabel';
export { default as MockDocumentWindow } from './MockDocumentWindow';
export { default as MockBrowserWindow } from './MockBrowserWindow';
export type { BrowserTab } from './MockBrowserWindow';
export { default as MockEmailWindow } from './MockEmailWindow';
export { default as MockChatInterface } from './MockChatInterface';
export { default as MockFinderWindow } from './MockFinderWindow';
export { default as FileIcon } from './FileIcon';
export { default as MockTextViewer } from './MockTextViewer';
export { default as AnimatedMouseCursor } from './AnimatedMouseCursor';
export { default as MockAmazonProductPage, PARODY_PRODUCTS } from './MockAmazonProductPage';
export { default as SimulatedMenuBar } from './SimulatedMenuBar';
export { default as VoiceTranscriptionOverlay } from './VoiceTranscriptionOverlay';
export type { FileType } from './FileIcon';
export type { ProductData } from './MockAmazonProductPage';