"""
Local Reasoning Models Registry.

Contains local reasoning models (GGUF via llama.cpp, HuggingFace transformers).
"""

from typing import Any, Dict, Optional

LOCAL_REASONING_PROVIDER_DISPLAY_ORDER: Dict[str, int] = {
    "qwen": 1,
    "google": 2,
    "microsoft": 3,
    "huggingface": 4,
    "mistral": 5,
    "solar": 6,
    "meta": 7,
}


def _local_generation(
    max_output: int,
    *,
    reasoning_mode: str = "tagged",
    activity_analysis: Optional[int] = None,
    agent_execution: Optional[int] = None,
    final_synthesis: Optional[int] = None,
    sampling: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    return {
        "reasoning_mode": reasoning_mode,
        "sampling": sampling
        or {
            "temperature": 0.1,
            "top_p": 0.95,
            "top_k": 40,
            "min_p": None,
            "repeat_penalty": 1.15,
        },
        "output_budgets": {
            "decision": min(512, max_output),
            "structured": min(2048, max_output),
            "narrative": min(2048, max_output),
            "activity_analysis": activity_analysis if activity_analysis is not None else min(4096, max_output),
            "general": min(4096, max_output),
            "agent_execution": agent_execution if agent_execution is not None else max_output,
            "final_synthesis": final_synthesis if final_synthesis is not None else max_output,
        },
    }


LOCAL_GGUF_MODELS: Dict[str, Any] = {
    "Qwen-qwen3-8b-instruct-q4km": {
        "handler": "llama_cpp",
        "location": "local",
        "provider": "qwen",
        "display_name": "Qwen3-8B Instruct Q4_K_M",
        "capabilities": ["reasoning"],
        "features": ["gpu_acceleration", "quantization", "function_calling"],
        "context_window": 40960,
        "max_output_tokens": 4000,
        "download_url": "https://huggingface.co/lm-kit/qwen-3-8b-instruct-gguf/resolve/main/Qwen3-8B-Q4_K_M.gguf",
        "on_disk_name": "qwen3-8b-instruct-q4km",
        "size": "5.03GB",
        "recommended_ram": "16GB",
        "speed_rating": 9,
        "accuracy_rating": 9,
        "recommended": True,
        "recommended_for_onboarding": True,
        "recommended_reason": "Best balance of speed and quality for local reasoning",
        # Plan B.2: opt this local model into hand-authored slim
        # descriptions/schemas. The construction layer reads this through
        # RuntimeModelProfile.tool_rendering and the LlamaCpp adapter
        # carries it into bind_tools without mutating descriptions.
        # Reversible: change to "full_schema" to revert.
        "tool_rendering": "slim_schema",
        "local_generation": _local_generation(4000),
    },
    "Qwen-qwen3-30b-a3b-q4km": {
        "handler": "llama_cpp",
        "location": "local",
        "provider": "qwen",
        "display_name": "Qwen3-30B-A3B Instruct Q4_K_M",
        "capabilities": ["reasoning"],
        "features": ["gpu_acceleration", "quantization", "function_calling"],
        "context_window": 40960,
        "max_output_tokens": 8192,
        "download_url": "https://huggingface.co/Qwen/Qwen3-30B-A3B-GGUF/resolve/main/Qwen3-30B-A3B-Q4_K_M.gguf",
        "on_disk_name": "qwen3-30b-a3b-q4km",
        "size": "18.6GB",
        "recommended_ram": "48GB",
        "speed_rating": 7,
        "accuracy_rating": 10,
        "recommended": False,
        "recommended_for_onboarding": False,
        "recommended_reason": "Higher-capacity local reasoning model for high-memory Apple Silicon",
        "tool_rendering": "slim_schema",
        "local_generation": _local_generation(8192),
    },
    "Qwen-qwen3-coder-30b-a3b-instruct-q4km": {
        "handler": "llama_cpp",
        "location": "local",
        "provider": "qwen",
        "display_name": "Qwen3-Coder-30B-A3B Instruct Q4_K_M",
        "capabilities": ["reasoning"],
        "features": ["gpu_acceleration", "quantization", "function_calling"],
        "context_window": 32768,
        "max_output_tokens": 65536,
        "download_url": "https://huggingface.co/unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF/resolve/main/Qwen3-Coder-30B-A3B-Instruct-Q4_K_M.gguf",
        "sha256": "fadc3e5f8d42bf7e894a785b05082e47daee4df26680389817e2093056f088ad",
        "on_disk_name": "qwen3-coder-30b-a3b-instruct-q4km",
        "size": "18.56GB",
        "recommended_ram": "48GB",
        "speed_rating": 7,
        "accuracy_rating": 10,
        "recommended": False,
        "recommended_for_onboarding": False,
        "recommended_reason": "Agentic coding model for high-memory local systems.",
        "tool_rendering": "slim_schema",
        "tool_call_format": "function_parameter_tags",
        "local_generation": {
            "reasoning_mode": "none",
            "sampling": {"temperature": 0.7, "top_p": 0.8, "top_k": 20, "min_p": None, "repeat_penalty": 1.05},
            "output_budgets": {"decision": 512, "structured": 2048, "narrative": 2048, "activity_analysis": 4096, "general": 4096, "agent_execution": 8192, "final_synthesis": 16384},
        },
    },
    "Qwen-qwen3-coder-next-q4km": {
        "handler": "llama_cpp",
        "location": "local",
        "provider": "qwen",
        "display_name": "Qwen3-Coder-Next Q4_K_M",
        "capabilities": ["reasoning"],
        "features": ["gpu_acceleration", "quantization", "function_calling"],
        "context_window": 32768,
        "max_output_tokens": 65536,
        "download_url": "https://huggingface.co/Qwen/Qwen3-Coder-Next-GGUF/resolve/main/Qwen3-Coder-Next-Q4_K_M/Qwen3-Coder-Next-Q4_K_M-00001-of-00004.gguf",
        "on_disk_name": "qwen3-coder-next-q4km",
        "artifact_root": "qwen3-coder-next-q4km",
        "primary_artifact": "Qwen3-Coder-Next-Q4_K_M-00001-of-00004.gguf",
        "artifact_files": [
            {"file": "Qwen3-Coder-Next-Q4_K_M-00001-of-00004.gguf", "download_url": "https://huggingface.co/Qwen/Qwen3-Coder-Next-GGUF/resolve/main/Qwen3-Coder-Next-Q4_K_M/Qwen3-Coder-Next-Q4_K_M-00001-of-00004.gguf", "sha256": "6bcfc9f9c37901eeb92172e2ab871224dab36a453d263bcb2547f737409534da", "size_bytes": 15524827040},
            {"file": "Qwen3-Coder-Next-Q4_K_M-00002-of-00004.gguf", "download_url": "https://huggingface.co/Qwen/Qwen3-Coder-Next-GGUF/resolve/main/Qwen3-Coder-Next-Q4_K_M/Qwen3-Coder-Next-Q4_K_M-00002-of-00004.gguf", "sha256": "817def0691ee9d08bf3dc4444be7aed29c9e52091e8fa9d97901ce7e7f6f01d3", "size_bytes": 14872168352},
            {"file": "Qwen3-Coder-Next-Q4_K_M-00003-of-00004.gguf", "download_url": "https://huggingface.co/Qwen/Qwen3-Coder-Next-GGUF/resolve/main/Qwen3-Coder-Next-Q4_K_M/Qwen3-Coder-Next-Q4_K_M-00003-of-00004.gguf", "sha256": "23aa634d47dca9b4ca3ea249384e6f01951b24c83cdc076f37f6f43d6c99883f", "size_bytes": 14503294496},
            {"file": "Qwen3-Coder-Next-Q4_K_M-00004-of-00004.gguf", "download_url": "https://huggingface.co/Qwen/Qwen3-Coder-Next-GGUF/resolve/main/Qwen3-Coder-Next-Q4_K_M/Qwen3-Coder-Next-Q4_K_M-00004-of-00004.gguf", "sha256": "249c768cc5f130dc731567d6edcbdacc48e14dec9e02c5dbe2b2185d2c5bdb2b", "size_bytes": 3510702144},
        ],
        "size": "48.41GB",
        "recommended_ram": "96GB",
        "speed_rating": 6,
        "accuracy_rating": 10,
        "recommended": False,
        "recommended_for_onboarding": False,
        "recommended_reason": "High-memory local coding agent model with a four-file GGUF installation.",
        "tool_rendering": "slim_schema",
        "tool_call_format": "function_parameter_tags",
        "local_generation": {
            "reasoning_mode": "none",
            "sampling": {"temperature": 1.0, "top_p": 0.95, "top_k": 40, "min_p": 0.0, "repeat_penalty": 1.0},
            "output_budgets": {"decision": 512, "structured": 2048, "narrative": 2048, "activity_analysis": 4096, "general": 4096, "agent_execution": 12288, "final_synthesis": 24576},
        },
    },
    "Qwen-qwen35-4b-q4km": {
        "handler": "llama_cpp",
        "location": "local",
        "provider": "qwen",
        "display_name": "Qwen3.5-4B Instruct Q4_K_M",
        "capabilities": ["reasoning"],
        "features": ["gpu_acceleration", "quantization", "function_calling"],
        "context_window": 262144,
        "max_output_tokens": 4096,
        "download_url": "https://huggingface.co/unsloth/Qwen3.5-4B-GGUF/resolve/main/Qwen3.5-4B-Q4_K_M.gguf",
        "on_disk_name": "qwen35-4b-q4km",
        "size": "2.78GB",
        "recommended_ram": "16GB",
        "speed_rating": 8,
        "accuracy_rating": 8,
        "recommended": False,
        "recommended_for_onboarding": False,
        "recommended_reason": "Compact current-generation Qwen model with long context for local reasoning",
        "tool_rendering": "slim_schema",
        "tool_call_format": "function_parameter_tags",
        "local_generation": _local_generation(4096, activity_analysis=1024),
    },
    "Qwen-qwen36-35b-a3b-ud-q4km": {
        "handler": "llama_cpp",
        "location": "local",
        "provider": "qwen",
        "display_name": "Qwen3.6-35B-A3B UD-Q4_K_M",
        "capabilities": ["reasoning"],
        "features": ["gpu_acceleration", "quantization", "function_calling"],
        "context_window": 262144,
        "max_output_tokens": 8192,
        "download_url": "https://huggingface.co/unsloth/Qwen3.6-35B-A3B-GGUF/resolve/main/Qwen3.6-35B-A3B-UD-Q4_K_M.gguf",
        "on_disk_name": "qwen36-35b-a3b-ud-q4km",
        "size": "18GB",
        "recommended_ram": "48GB",
        "speed_rating": 6,
        "accuracy_rating": 10,
        "recommended": False,
        "recommended_for_onboarding": False,
        "recommended_reason": "High-capability Qwen3.6 MoE candidate for high-memory Apple Silicon",
        "tool_rendering": "slim_schema",
        "tool_call_format": "function_parameter_tags",
        "local_generation": _local_generation(8192),
    },
    "Google-gemma4-e4b-it-qat-q4_0": {
        "handler": "llama_cpp",
        "location": "local",
        "provider": "google",
        "display_name": "Gemma 4 E4B IT QAT Q4_0",
        "capabilities": ["reasoning"],
        "features": ["gpu_acceleration", "quantization"],
        "context_window": 128000,
        "max_output_tokens": 4096,
        "download_url": "https://huggingface.co/google/gemma-4-E4B-it-qat-q4_0-gguf/resolve/main/gemma-4-E4B_q4_0-it.gguf",
        "on_disk_name": "gemma4-e4b-it-qat-q4_0",
        "size": "5.15GB",
        "recommended_ram": "16GB",
        "speed_rating": 7,
        "accuracy_rating": 8,
        "recommended": False,
        "recommended_for_onboarding": False,
        "recommended_reason": "Official QAT GGUF Google-family model for efficient local reasoning",
        "local_generation": _local_generation(4096),
    },
    "Microsoft-phi4-mini-q4km": {
        "handler": "llama_cpp",
        "location": "local",
        "provider": "microsoft",
        "display_name": "Phi-4 Mini Instruct Q4_K_M",
        "capabilities": ["reasoning"],
        "features": ["gpu_acceleration", "quantization", "function_calling"],
        "context_window": 128000,
        "max_output_tokens": 4096,
        "download_url": "https://huggingface.co/tensorblock/Phi-4-mini-instruct-GGUF/resolve/main/Phi-4-mini-instruct-Q4_K_M.gguf",
        "on_disk_name": "phi4-mini-instruct-q4km",
        "size": "2.49GB",
        "recommended_ram": "16GB",
        "speed_rating": 8,
        "accuracy_rating": 8,
        "recommended": False,
        "recommended_for_onboarding": False,
        "recommended_reason": "Compact reasoning and coding model with 128K context",
        "local_generation": _local_generation(4096),
    },
    "HuggingFace-smollm3-3b-q4km": {
        "handler": "llama_cpp",
        "location": "local",
        "provider": "huggingface",
        "display_name": "SmolLM3-3B Q4_K_M",
        "capabilities": ["reasoning"],
        "features": ["gpu_acceleration", "quantization", "function_calling"],
        "context_window": 128000,
        "max_output_tokens": 4096,
        "download_url": "https://huggingface.co/Edge-Quant/SmolLM3-3B-Q4_K_M-GGUF/resolve/main/smollm3-3b-q4_k_m.gguf",
        "on_disk_name": "smollm3-3b-q4km",
        "size": "1.92GB",
        "recommended_ram": "16GB",
        "speed_rating": 9,
        "accuracy_rating": 7,
        "recommended": False,
        "recommended_for_onboarding": False,
        "recommended_reason": "Fully open compact model for low-memory local reasoning workflows",
        "local_generation": _local_generation(4096),
    },
    "Mistral-mistral-nemo": {
        "handler": "llama_cpp",
        "location": "local",
        "provider": "mistral",
        "display_name": "Mistral Nemo Base 2407",
        "capabilities": ["reasoning"],
        "features": ["gpu_acceleration"],
        "context_window": 128000,
        "max_output_tokens": 4000,
        "download_url": "https://huggingface.co/PJMixers-Dev/mistralai_Mistral-Nemo-Base-2407-ungated/resolve/main/consolidated.safetensors",
        "on_disk_name": "mistral-nemo",
        "size": "24.5GB",
        "recommended_ram": "24GB",
        "speed_rating": 4,
        "accuracy_rating": 9,
        "local_generation": _local_generation(4000),
    },
    "Solar-solar": {
        "handler": "llama_cpp",
        "location": "local",
        "provider": "solar",
        "display_name": "SOLAR 10.7B Instruct",
        "capabilities": ["reasoning"],
        "features": ["gpu_acceleration", "quantization"],
        "context_window": 4096,
        "max_output_tokens": 2000,
        "download_url": "https://huggingface.co/TheBloke/SOLAR-10.7B-Instruct-v1.0-GGUF/resolve/main/solar-10.7b-instruct-v1.0.Q4_K_M.gguf",
        "on_disk_name": "solar-base",
        "size": "6.46GB",
        "recommended_ram": "16GB",
        "speed_rating": 5,
        "accuracy_rating": 8,
        "local_generation": _local_generation(2000),
    },
}

LOCAL_HF_MODELS: Dict[str, Any] = {
    "Qwen-qwen3-4b": {
        "handler": "huggingface",
        "location": "local",
        "provider": "qwen",
        "display_name": "Qwen3-4B Instruct",
        "capabilities": ["reasoning"],
        "features": ["gpu_acceleration"],
        "context_window": 32768,
        "max_output_tokens": 4000,
        "repo_url": "https://huggingface.co/Qwen/Qwen3-4B",
        "revision": "main",
        "on_disk_name": "qwen3-4b-base",
        "size": "8.05GB",
        "recommended_ram": "16GB",
        "speed_rating": 7,
        "accuracy_rating": 8,
        "local_generation": _local_generation(4000),
    },
    "Mistral-mistral-7b-v03": {
        "handler": "huggingface",
        "location": "local",
        "provider": "mistral",
        "display_name": "Mistral 7B v0.3",
        "capabilities": ["reasoning"],
        "features": ["gpu_acceleration"],
        "context_window": 32768,
        "max_output_tokens": 2000,
        "repo_url": "https://huggingface.co/AIsley/Mistral-7B-v0.3",
        "revision": "main",
        "on_disk_name": "mistral-7b-v03",
        "size": "14.5GB",
        "recommended_ram": "32GB",
        "speed_rating": 3,
        "accuracy_rating": 8,
        "local_generation": _local_generation(2000),
    },
}
