from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional
import logging
from pathlib import Path
import time

from api.services.capture.shared.window_capture_bridge import (
    deliver_capture_response,
    request_swift_window_capture,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/capture", tags=["capture"])

# Response Models
class CaptureResultResponse(BaseModel):
    """Response model for capture operations."""
    success: bool
    message: Optional[str] = None
    image_path: Optional[str] = None
    app_name: Optional[str] = None
    window_title: Optional[str] = None
    timestamp: Optional[int] = None  # Unix milliseconds, generated by Swift client
    capture_method: Optional[str] = None
    has_image: Optional[bool] = None
    timeout_duration: Optional[float] = None

class CaptureResponseAckResponse(BaseModel):
    """Response model for capture response acknowledgment."""
    status: str
    message: str

@router.post("/swift-window", response_model=CaptureResultResponse)
async def trigger_swift_window_capture() -> CaptureResultResponse:
    """
    Trigger Swift WindowCaptureService to capture the current active window.
    
    This endpoint is designed to be called immediately when a wake word is detected
    to capture the screen context before the user navigates away.
    
    Returns:
        JSON response with capture results including file path
    """
    try:
        # Call the frontend Swift app to perform the capture
        # This uses the working WindowCaptureService that has proper permissions
        
        # For now, we'll use a simple HTTP call to trigger the Swift capture
        # The Swift app should provide an endpoint for this
        # TODO: Implement the Swift endpoint to handle this request
        
        logger.info("🔍 Triggering Swift window capture for wake word context")
        
        # This is a placeholder - we need to implement the Swift side endpoint
        # For now, return a mock response structure that matches what we expect
        timestamp = int(time.time() * 1000)  # Unix milliseconds
        temp_dir = Path.home() / ".basil" / "data" / "temp"
        temp_dir.mkdir(parents=True, exist_ok=True)
        
        # The actual implementation will call Swift, but for now we prepare the structure
        return CaptureResultResponse(
            success=True,
            image_path=None,  # Will be filled by Swift capture
            app_name="Unknown",
            window_title="Unknown",
            timestamp=timestamp,
            capture_method="swift_window_service"
        )
        
    except Exception as e:
        logger.error(f"❌ Failed to trigger Swift window capture: {e}")
        raise HTTPException(
            status_code=500, 
            detail=f"Failed to trigger Swift window capture: {str(e)}"
        )

@router.post("/swift-window-immediate", response_model=CaptureResultResponse)
async def trigger_swift_window_capture_immediate() -> CaptureResultResponse:
    """
    Trigger Swift WindowCaptureService to capture the current active window via WebSocket.
    
    This endpoint sends a WebSocket message to the frontend requesting an immediate capture,
    then waits for the frontend to respond with the capture results.
    
    Returns:
        JSON response with capture results including file path
    """
    result = await request_swift_window_capture("agent_task")
    return CaptureResultResponse(**result)

@router.post("/capture-response", response_model=CaptureResponseAckResponse)
async def handle_capture_response(response_data: dict) -> CaptureResponseAckResponse:
    """
    Handle capture response from the frontend Swift app.
    
    This endpoint receives the results of a capture request that was sent via WebSocket.
    """
    try:
        deliver_capture_response(response_data)
        return CaptureResponseAckResponse(
            status="success",
            message="Capture response received"
        )
        
    except Exception as e:
        logger.error(f"❌ Error handling capture response: {e}")
        raise HTTPException(status_code=500, detail=f"Error handling capture response: {str(e)}")
